### ISSUE TITLE
New quest: Craft a demo

### ISSUE THREAD

**Issue by Offirmo** [Domenicobrz/legendary-cursor#1]
An avid RPG fan is wanting a demo.

He is ready to reward you for your efforts.

Reward: 1 GitHub star + sharing to his 1K developer colleagues at work

Do you accept this quest? Yes / No

**Comment by Domenicobrz** [comment]
What kind of demo? :)
You can already try it here:
https://domenicobrz.github.io/webgl/index.html

**Comment by Offirmo** [comment]
Ah I missed the «demo» section at the end of the README.

My mistake.

You may want to move it closer to the top, like most libs do.

**Comment by Domenicobrz** [comment]
I've added it today after your response that's why you missed it 😁

**Comment by Offirmo** [comment]
Quest validated, you have my star!
